### ISSUE TITLE
__eq__ on Any returns Any instead of bool

### ISSUE THREAD

**Issue by Fogapod** [python/mypy#12201]
**Bug Report**

Using comparison operator on Any type returns Any instead of bool.

**To Reproduce**

```python
from typing import Any

a: Any = 1

reveal_type(a == 1)  # Any
reveal_type(1 == a)  # Any
```

**Expected Behavior**

```python
from typing import Any

a: Any = 1

reveal_type(a == 1)  # bool or maybe Any since we don't know what Any.__eq__(int) will do?
reveal_type(1 == a)  # bool
```

**Actual Behavior**

Results of comparisons are Any.

**Your Environment**

- Mypy version used: `0.931`
- Mypy command-line flags: none
- Mypy configuration options from `mypy.ini` (and other config files):
```toml
[tool.mypy]
python_version = "3.7"

show_column_numbers = true
show_error_codes = true

# same as mypy --strict
disallow_subclassing_any = true
disallow_any_generics = true
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
warn_unused_ignores = true
warn_return_any = true
no_implicit_reexport = true
strict_equality = true
```
- Python version used: `3.7.12`
- Operating system and version: `Arch Linux, 5.16.7-arch1-1`
