### ISSUE TITLE
(🐞) Mypy doesn't use `python_executable` to find plugins

### ISSUE THREAD

**Issue by KotlinIsland** [python/mypy#12575]
```toml
[tool.mypy]
python_executable = ".venv/bin/python"
plugins = ["pydantic.mypy"]
```

```py
# test.py
import pydantic
```
```
(.venv) > mypy test.py
Success: no issues found in 1 source file
(.venv) > deactivate
...
> mypy test.py
pyproject.toml:1: error: Error importing plugin "pydantic.mypy": No module named 'pydantic'
Found 1 error in 1 file (errors prevented further checking)
```
