### ISSUE TITLE
Support FORCE_COLOR in addition to MYPY_FORCE_COLOR

### ISSUE THREAD

**Issue by hugovk** [python/mypy#13806]
**Feature**

Force colour when the `FORCE_COLOR` environment variable is set.

**Pitch**

Mypy automatically adds colour to output for TTYs, or if the env var `MYPY_FORCE_COLOR` is set.

For example, GitHub Actions is not a tty but it's good to add colour to help read the logs.

`FORCE_COLOR` is used by many CLI tools and libraries.

It would be good if mypy forced colour output if either `FORCE_COLOR` or `MYPY_FORCE_COLOR` is set.

This helps avoid adding lots of separate env vars for each tool/CLI, [for example](https://github.com/jazzband/pip-tools/pull/1691):

```yml
env:
  FORCE_COLOR: 1 # Request colored output from CLI tools supporting it
  MYPY_FORCE_COLOR: 1 # MyPy's color enforcement
  PIP_DISABLE_PIP_VERSION_CHECK: 1
  PIP_NO_PYTHON_VERSION_WARNING: 1
  PIP_NO_WARN_SCRIPT_LOCATION: 1
  PY_COLORS: 1 # Recognized by the `py` package, dependency of `pytest`
  TOX_PARALLEL_NO_SPINNER: 1
  TOX_TESTENV_PASSENV: >-
    FORCE_COLOR
    MYPY_FORCE_COLOR
    NO_COLOR
    PY_COLORS
    PYTEST_THEME
    PYTEST_THEME_MODE
```

For reference:

* pytest [issue](https://github.com/pytest-dev/pytest/issues/7464), [PR](https://github.com/pytest-dev/pytest/pull/7466) and [docs](https://pytest.org/en/7.0.x/reference/reference.html#environment-variables)
* nox [issue](https://github.com/theacodes/nox/issues/502) and [PR](https://github.com/theacodes/nox/pull/524)
* tox [PR](https://github.com/tox-dev/tox/pull/1630)
* rich [release](https://github.com/Textualize/rich/releases/tag/v12.6.0), [issue](https://github.com/Textualize/rich/issues/2425) and [PR](https://github.com/Textualize/rich/pull/2449)
* pypa/build [PR](https://github.com/pypa/build/pull/335)
* Node.js [docs](https://nodejs.org/api/tty.html#writestreamgetcolordepthenv)
