### ISSUE TITLE
MYPY_FORCE_COLOR only colours output on Windows, not macOS/Ubuntu

### ISSUE THREAD

**Issue by hugovk** [python/mypy#13817]
**Bug Report**

When using `MYPY_FORCE_COLOR` (or `FORCE_COLOR` with `master`) on GitHub Actions (which is not a tty), colour only shows up for Windows, and not for Ubuntu or macOS.

**To Reproduce**

Test with a worklflow something like this:

```yml
name: Test

on: [push, pull_request, workflow_dispatch]

env:
  MYPY_FORCE_COLOR: 1

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [
          "3.7",
          "3.10",
        ]
        os: [
          windows-latest,
          macOS-latest,
          ubuntu-latest,
        ]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install mypy

      - name: Test
        run: |
          mypy test.py
```

**Expected Behavior**

Colour output for all three operating systems.

**Actual Behavior**

Colour output only for Windows:

<img width="723" alt="image" src="https://user-images.githubusercontent.com/1324225/193943018-f832b8ce-3ec1-4119-9601-c0fad69e748b.png">

And not for Ubuntu:

<img width="720" alt="image" src="https://user-images.githubusercontent.com/1324225/193943354-08c5222e-45ce-4f6c-984a-dd400c36928d.png">

Nor macOS:

<img width="717" alt="image" src="https://user-images.githubusercontent.com/1324225/193943321-4a65cb82-5905-4c02-8e91-c887a7c9ca07.png">

For example: https://github.com/hugovk/test/actions/runs/3185917456

**Your Environment**

- Mypy version used: 0.982
- Mypy command-line flags: none
- Mypy configuration options from `mypy.ini` (and other config files): none
- Python version used: 3.7 and 3.10
