### ISSUE TITLE
python 3.10 in CI, mypy checks files in site-packages

### ISSUE THREAD

**Issue by copdips** [python/mypy#13882]
**Bug Report**

Hello,
I'm using Azure pipeline agent with `python 3.10`. with latest mypy version triggered by pre-commit, with pyproject.toml config file.
I installed all the python packages without venv, as it's a CI agent.
During the pre-commit check, it throws mypy error on:

```bash
/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/site-packages/pandas-stubs/core/series.pyi:314: error: Positional-only parameters are only supported in Python 3.8 and greater  [syntax]
```
For Azure pipeline agent with python `3.8` and `3.9`, there's no such error.

And I also tried multiple options to exclude the file by pattern `site-packages` in the config file `pyproject.toml` as per this [doc](https://mypy.readthedocs.io/en/stable/config_file.html#example-pyproject-toml), none of them works, could anybody provides the correct the exclude syntax in `pyproject.toml` to exclude files by path keyword, which in my case `/site-packages/`

**To Reproduce**

See above bug report section

**Expected Behavior**

No cheks for files in site-packages

**Actual Behavior**

Mypy checks files in python packages

**Your Environment**

- Mypy version used: 0.961
- Mypy command-line flags:
- Mypy configuration options from `mypy.ini` (and other config files):
- Python version used: Python3.10.7

```toml
# file pyproject.toml
[tool.mypy]
ignore_missing_imports = true
warn_return_any = true
warn_unused_configs = true
```

```yaml
# file .pre-commit-config.yaml
- repos:
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        language: system
        entry: mypy
        types: [python]
        args:
          - --show-error-codes
```
