### ISSUE TITLE
better doc on excluding files in pyproject.toml

### ISSUE THREAD

**Issue by copdips** [python/mypy#13883]
**Documentation**

hello,

Could anyone provide a better doc about the exculde section in the pyproject.toml file ?

Current doc [says](https://mypy.readthedocs.io/en/stable/config_file.html#example-pyproject-toml):

```yaml
[tool.mypy]
python_version = "2.7"
warn_return_any = true
warn_unused_configs = true
exclude = [
    '^file1\.py$',  # TOML literal string (single-quotes, no escaping necessary)
    "^file2\\.py$",  # TOML basic string (double-quotes, backslash and other characters need escaping)
]
```

IMHO, it's not very clear, at least, it should explain what kind of files are exclude by the syntax of `'^file1\.py$'`, and what for `"^file2\\.py$"`. And is it for any file with the same name under any folder ?
In addition, could you please provide an example how to exclude by a file path keywork. Suppose i have some files located at :  `/a/b/c/file.py`,  I would like to exclude all files where their location has the keywork `/c/`, how to achieve that.

**Comment by hauntsaninja** [comment]
See https://mypy.readthedocs.io/en/stable/config_file.html#confval-exclude

**Comment by copdips** [comment]
Thanks, in fact, I'm using `pyproject.toml` with mypy in `pre-commit`.
It seems that the exclusion declared in `pyproject.toml` works well when running mypy directly out of `pre-commit`, but doesn't work when with `pre-commit`.

I intentionaly make a file (`venv/pyodbc.pyi`) in my venv with mypy error, and also a  real python file inside of the project (`scripts/test_sleep.py`) with mypy error too.

My `pyproject.toml` conf looks like:

```toml
[tool.mypy]
exclude = [
    "^venv/",
    "^scripts/",
]
```

Running `mypy .` with venv activated, it doesn't show the errors on the two file, it's expected, as both of the files are excluded in `pyproject.toml`, and by commenting the exclude part, `mypy .` can show the errors on the two file, till now, all good.

Now running mypy under pre-commit, `.pre-commit-config.yaml` looks like:

```yaml
repos:
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        language: system
        entry: mypy
        types: [python]
        args:
          - --show-error-codes
```

Running `pre-commit run mypy --all-files` (always with venv activated) shows only the error in the file `scripts/test_sleep.py` no matter I comment or uncomment the exclude part in `pyproject.toml`, and the type error in `venv/pyodbc.pyi` is never shown neither.

Adding config-file param in `.pre-commit-config.yaml` doesn't help neither:

```yaml
repos:
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        language: system
        entry: mypy
        types: [python]
        args:
          - --show-error-codes
          - --config-file
          - pyproject.toml
```

**Comment by hauntsaninja** [comment]
Use pass_filenames: false. mypy does whole program analysis so pre-commits file diffing isn't saving you work

**Comment by hauntsaninja** [comment]
https://github.com/python/mypy/issues/13916

**Comment by copdips** [comment]
> #13916

thx a lot

**Comment by tgy** [comment]
i have the same issue... running `pre-commit run mypy -a` is completely discarding my `exclude` rules in my `pyproject.toml` file

**Comment by pedropaulofb** [comment]
> > #13916
> 
> thx a lot, but with the suggested param, I got the error:
> 
> ```shell
> mypy.....................................................................Failed
> - hook id: mypy
> - exit code: 2
> 
> usage: mypy [-h] [-v] [-V] [more options; see below]
>             [-m MODULE] [-p PACKAGE] [-c PROGRAM_TEXT] [files ...]
> mypy: error: Missing target module, package, files, or command.
> ```
> 
> removing the `pass_filenames: false` from the hook removes the error.

I have the same problem. @copdips or @tgy, could you solve the problem? May I ask you how? Thanks in advance.

**Comment by copdips** [comment]
Hello,

to be honnest, I haven't used mypy for a while, what I can show is my last config, I don't run mypy directly, always from pre-commit.

```toml
# file pyproject.toml

[tool.mypy]
ignore_missing_imports = true
warn_return_any = true
warn_unused_configs = true
show_error_codes = true
# strict = true
exclude = ["^.venv/", "^build/", "^_local_test/"]
```

```yaml
# file .pre-commit-config.yaml

- id: mypy
  name: mypy
  language: system
  entry: mypy
  types: [python]
```
