### ISSUE TITLE
dmypy does not work right with 

### ISSUE THREAD

**Issue by uf-fipper** [python/mypy#14241]
**Bug Report**

dmypy doesn't support `disable_error_code` and `enable_error_code` key in `pyproject.toml/mypy.ini`?

in `pyproject.toml`:
```toml
# pyproject.toml
[tool.mypy]
disable_error_code = ['var-annotated']
```

run: `dmypy run a.py`
output: `Timed out waiting for daemon to start`

But when `disable_error_code = []` or doesn't has `disable_error_code`, dmypy work right.

**Your Environment**

- Mypy version used: 0.981, 0.991
- Mypy command-line flags: dmypy run a/a.py
- Mypy configuration options from `pyproject.toml`: `disable_error_code = ['var-annotated']`
- Python version used: 3.11
