### ISSUE TITLE
Daemon `dmypy` crashes with `disable_error_code` configuration option

### ISSUE THREAD

**Issue by LukeSavefrogs** [python/mypy#14671]
## Description 
Evertything was working until i tried to disable some error codes using the `disable_error_code = 'no-untyped-def,empty-body'` option in the `pyproject.toml` file. 

After restarting the daemon, it crashed with the error `Timed out waiting for daemon to start`

**Log**
```
Mypy extension activated, version 0.2.3
Registering listener for interpreter changed event
Listener registered
[1] Check folder: c:\Users\lucas\Desktop\myFolder
Activation complete
[1] Received python path from Python extension: C:\Python39\python.exe
[1] Running dmypy in folder c:\Users\lucas\Desktop\myFolder
'C:\Python39\Scripts\dmypy.EXE' --status-file 'c:\Users\lucas\AppData\Roaming\Code\User\workspaceStorage\41737679a5dd5649bc304b3214d8b429\matangover.mypy\dmypy-6e071d9aa88ca0124b79d66d19a862665ea10e28-14032.json' run --log-file 'c:\Users\lucas\AppData\Roaming\Code\User\workspaceStorage\41737679a5dd5649bc304b3214d8b429\matangover.mypy\dmypy-6e071d9aa88ca0124b79d66d19a862665ea10e28.log' -- . --show-column-numbers --no-error-summary --no-pretty --no-color-output --python-executable 'C:\Python39\python.exe'
[1] stderr:
Timed out waiting for daemon to start

[1] Error running mypy in c:\Users\lucas\Desktop\myFolder: mypy failed with error: "Timed out waiting for daemon to start
". See Output panel for details.
```

**To Reproduce**

Use the `disable_error_code` configuration option either in the `pyproject.toml` or in the `mypy.ini` files.

**Your Environment**

- Mypy version used: `mypy 1.0.0 (compiled: yes)`
- Mypy command-line flags: I used the _vscode extension_ [Mypy](https://marketplace.visualstudio.com/items?itemName=matangover.mypy) 
- Mypy configuration options from `mypy.ini` (and other config files):
  ```toml
  # Inside `pyproject.toml`...
  [tool.mypy]
  strict = true
  warn_no_return = false
  warn_return_any = false
  disallow_untyped_defs = false
  warn_incomplete_stub = false
  
  disable_error_code = 'no-untyped-def,empty-body'
  ```
- Python version used: `Python 3.9.6`
- Operating system and version: `Windows 10 (version 10.0.19044 Build 19044)`
