### ISSUE TITLE
Allow redefinition does not always work

### ISSUE THREAD

**Issue by filips123** [python/mypy#15101]
**Bug Report**

In some cases, mypy will disallow variable redefinition, even when "allow redefinition" is enabled and the variable has been read.

**To Reproduce**

Here is the code snippet:

```py
def get_menus(date: datetime.date) -> dict[str, Optional[dict[str, str]]]:
    # SnackMenu and LunchMenu are SQLAlchemy 2.0 models
    snack = Session.query(SnackMenu).filter(SnackMenu.date == date).first()
    lunch = Session.query(LunchMenu).filter(LunchMenu.date == date).first()

    reveal_type(snack)  # Revealed type is "Union[gimvicurnik.database.SnackMenu, None]"
    reveal_type(lunch)  # Revealed type is "Union[gimvicurnik.database.LunchMenu, None]"

    if snack:
        snack = {
            "normal": snack.normal,
            "poultry": snack.poultry,
            "vegetarian": snack.vegetarian,
            "fruitvegetable": snack.fruitvegetable,
        }

    if lunch:
        lunch = {
            "normal": lunch.normal,
            "vegetarian": lunch.vegetarian,
        }

    return {
        "snack": snack,
        "lunch": lunch,
    }
```

Here is the mypy config:

```toml
[tool.mypy]
python_version = 3.9
show_column_numbers = true
show_error_codes = true
allow_redefinition = true
disallow_untyped_decorators = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_configs = true
warn_unused_ignores = true
warn_no_return = true
warn_return_any = true
warn_unreachable = true
```

**Expected Behavior**

As "allow redefinition" is enabled and the variable as been read, this code should not produce any errors. Mypy should determine that the type of `snack` and `lunch` variable has been changed to `Union[Dict[str, str], None]` after `if` statements and allow assigments.

**Actual Behavior**

Mypy produces the following errors:

```
gimvicurnik\blueprints\menus.py:29:25: error: Incompatible types in assignment (expression has type "Dict[str, Optional[str]]", variable has type "Optional[SnackMenu]")  [assignment]
gimvicurnik\blueprints\menus.py:37:25: error: Incompatible types in assignment (expression has type "Dict[str, Optional[str]]", variable has type "Optional[LunchMenu]")  [assignment]
gimvicurnik\blueprints\menus.py:43:17: error: Dict entry 0 has incompatible type "str": "Optional[SnackMenu]"; expected "str": "Optional[Dict[str, str]]"  [dict-item]
gimvicurnik\blueprints\menus.py:44:17: error: Dict entry 1 has incompatible type "str": "Optional[LunchMenu]"; expected "str": "Optional[Dict[str, str]]"  [dict-item]
```

**Your Environment**

- Mypy version used: 1.2.0
- Python version used: 3.10
