### ISSUE TITLE
Error with identical actual and expected types on @wraps

### ISSUE THREAD

**Issue by berzi** [python/mypy#15329]
**Bug Report**

> error: Argument 1 to "__call__" of "IdentityFunction" has incompatible type
"Callable[T_Params, Tuple[Order, List[OrderItem]]]"; expected "Callable[T_Params, Tuple[Order, List[OrderItem]]]"  [arg-type]

On the following code:
```py
T_Params = ParamSpec("T_Params")
OrderAndItems: TypeAlias = tuple[Order, list[OrderItem]]
CallableReturnsOrderAndItems: TypeAlias = Callable[T_Params, OrderAndItems]


def my_decorator(func: CallableReturnsOrderAndItems) -> CallableReturnsOrderAndItems:
    @wraps(func)
    def wrapper(*args: T_Params.args, **kwargs: T_Params.kwargs) -> OrderAndItems:
        order, items = func(*args, **kwargs)

        # ... irrelevant code ...

        return order, items

    return wrapper
```

Maybe I'm misusing ParamSpec in some way; if I am, I'm unsure how and I think the error message should be improved.
If i'm not, then this is likely a bug.

**To Reproduce**

See code above, replace the `Order` and `OrderItem` types with any valid type.

**Actual Behavior**

On `@wraps`:

> error: Argument 1 to "__call__" of "IdentityFunction" has incompatible type
"Callable[T_Params, Tuple[Order, List[OrderItem]]]"; expected "Callable[T_Params, Tuple[Order, List[OrderItem]]]"  [arg-type]

**Your Environment**

- Mypy version used: mypy 1.3.0 (compiled: yes)
- Mypy command-line flags: -
- Python version used: 3.10.11
- Mypy configuration options from `mypy.ini` (and other config files):
```toml
[tool.mypy]
disable_error_code = [
    "misc",
]
no_implicit_optional = true
strict_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_no_return = true
local_partial_types = true
strict_concatenate = true
strict_equality = true
warn_unreachable = true
check_untyped_defs = true
warn_return_any = true
```
