### ISSUE TITLE
With v1.4 module-global variables become fixed in type.

### ISSUE THREAD

**Issue by jenstroeger** [python/mypy#15533]
This seems to be a regression with v1.4 of mypy.

It looks to me like globals are considered constant if they’re not explicitly typed. For example (see issue https://github.com/Bogdanp/dramatiq/issues/555) a module-global variable like
```python
global_broker = None
```
seems to be typed now as `None`. Consequently reading that variable and then asserting its value is always false and therefore raises an exception
```python
broker = some.module.global_broker
assert broker is not None  # Previously this worked; now it's considered None and therefore raises.
```
and that means that the next statement
```python
broker.enqueue(message, delay=delay)
```
becomes unreachable.

I therefore changed the module-global variable declaration to
```python
global_broker: Optional["Broker"] = None
```
which solved the problem. However, that’s in an external module and therefore my own code is now broken after updating to v1.4 of  mypy.

Would it make sense to consider the type for such a module-global variable as `Any | None` (or just `Any`) instead of just `None`?  (Assuming that a module-global `None` variable will change.)

**To Reproduce**

See above.

**Expected Behavior**

As with v1.3 I would have expected mypy to pass the type check.

**Actual Behavior**

With v1.4 mypy now flags the statement following the `assert` as unreachable.

**Your Environment**

- Mypy version used: mypy 1.4.1
- Mypy configuration options from `mypy.ini` (and other config files):
   ```toml
    [tool.mypy]
    show_error_codes = true
    show_column_numbers = true
    check_untyped_defs = true
    incremental = false
    strict_equality = true
    warn_return_any = true
    warn_redundant_casts = true
    warn_unreachable = true
    warn_unused_configs = true
    warn_unused_ignores = true
    disallow_untyped_calls = true
    disallow_untyped_defs = true
    disallow_incomplete_defs = true
    disallow_untyped_decorators = true
    disable_error_code = []
    plugins = "sqlalchemy.ext.mypy.plugin"
   ```
- Python version used: 3.10.12
