### ISSUE TITLE
False positive with strict_optional disabled just in submodule

### ISSUE THREAD

**Issue by Garrett-R** [python/mypy#15914]
**Bug Report**

(A clear and concise description of what the bug is.)

**To Reproduce**

The simplest example I got is the below setup, which I also attach [here](https://github.com/python/mypy/files/12386707/mypy_repro.zip) for convenience.

Directory structure:
```
.
├── my_subdir
│   ├── dog.py
│   └── __init__.py
├── pyproject.toml
└── repro.py
```
 and the files are:
 
 ```toml
 [tool.poetry.dependencies]
python = "^3.11.2"


[tool.poetry.dev-dependencies]
mypy = "1.5.1"


[tool.mypy]
strict_optional = true


[[tool.mypy.overrides]]
module = "my_subdir.*"
strict_optional = false
 ```
 
 ```python
# dog.py
from dataclasses import dataclass

@dataclass
class Dog:
    height: float | None
```

```python
# repro.py
from my_subdir.dog import Dog

height: float | None = 1.0
Dog(height)
```

Now, enter command: `mypy repro.py`.

**Expected Behavior**

No errors

**Actual Behavior**

```python
repro.py:4: error: Argument 1 to "Dog" has incompatible type "float | None"; expected "float"  [arg-type]
```

**Your Environment**

- Mypy version used: 1.5.1
- Mypy command-line flags:  _none)
- Python version used: 3.11.4
