### ISSUE TITLE
INTERNAL ERROR when using `mypy==0.991` with `fastapi==0.103.1`

### ISSUE THREAD

**Issue by CallumJHays** [python/mypy#16213]
**Bug Report**
Internal error is being thrown when trying to use mypy `0.991` with fastapi `0.103.1`. Older versions of fastapi (`0.88`) do not have any issues, indicating the error was introduced by fastapi. I can update to mypy `1.5` and will do so, but figured it would be good to document this bug.

**To Reproduce**

```
$ pip install mypy==0.991 fastapi==0.103.1
$ poetry run mypy --disallow-untyped-defs app --show-traceback
```

**Actual Behavior**

```
.../.venv/lib/python3.10/site-packages/fastapi/openapi/models.py:281: error: INTERNAL ERROR -- Please try using mypy master on GitHub:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 0.991
Traceback (most recent call last):
  File "mypy/checker.py", line 573, in accept
  File "mypy/nodes.py", line 1143, in accept
  File "mypy/checker.py", line 2127, in visit_class_def
AttributeError: attribute 'mro' of 'TypeInfo' undefined
```

The line triggering the issue is the `class Config:` line within this code snippet, https://github.com/tiangolo/fastapi/blob/master/fastapi/openapi/models.py#L281
```python
class Example(TypedDict, total=False):
    summary: Optional[str]
    description: Optional[str]
    value: Optional[Any]
    externalValue: Optional[AnyUrl]

    if PYDANTIC_V2:  # type: ignore [misc]
        __pydantic_config__ = {"extra": "allow"}

    else:

        class Config:
            extra = "allow"
```

**Your Environment**

- Python version used: `3.10.13`
- Mypy version used: `0.991`
- Mypy command-line flags: `--disallow-untyped-defs --show-traceback`
- `mypy.ini`:
  ```toml
  [mypy]
  plugins = numpy.typing.mypy_plugin
  
  [mypy-boto3.*]
  ignore_missing_imports = True
  
  [mypy-tqdm.*]
  ignore_missing_imports = True
  
  [mypy-faiss.*]
  ignore_missing_imports = True
  
  [mypy-flaky.*]
  ignore_missing_imports = True
  
  [mypy-numpy.*]
  ignore_missing_imports = True
  
  [mypy-uvicorn.*]
  ignore_missing_imports = True
  
  [mypy-sentence_transformers.*]
  ignore_missing_imports = True
  
  [mypy-importlib_metadata.*]
  ignore_missing_imports = True
  ```
