### ISSUE TITLE
`mutable-override`: does it exist?

### ISSUE THREAD

**Issue by jamesbraza** [python/mypy#16882]
**Bug Report**

Coming from https://mypy.readthedocs.io/en/stable/error_code_list2.html#check-that-overrides-of-mutable-attributes-are-safe, with `mypy==1.7.1`, Python 3.10.13, and the below config:

```toml
[tool.mypy]
enable_error_code = ["mutable-override"]
``` 

I get the below error when running `mypy`:

```none
pyproject.toml: [mypy]: enable_error_code: Invalid error code(s): mutable-override
```

Does `mutable-override` even exist?
