### ISSUE TITLE
Errors when narrowing `str | None` to `Literal[str]`

### ISSUE THREAD

**Issue by nicholasjng** [python/mypy#16916]
**Bug Report**

Apologies if this is well known, I searched the issues and did not find what I was looking for.

TL,DR: In my mind, the repro below should work.

**To Reproduce**

```python
from typing import Literal


class A:
    def b(self, driver: str | None):
        ...


class B(A):
    def b(self, driver: Literal["json", "csv", "parquet"]):
        ...
```

My reasoning is that `driver` on method `B.b()` is a string literal with only three allowed values, which is a legal subset of what the supertype allows (i.e., any string or None).

Background for my use case is that I have a class taking a `driver` argument which is then essentially looked up in a dictionary with `str` keys. Since the set of its keys is not static, the type cannot be reasonably narrowed to a literal. `None` means that the driver will be inferred from a different argument, which I omitted here since it's not interesting.

I now have a subclass which can only deal with a limited subset of drivers, which are statically known, so I tried narrowing them as much as possible.

**Expected Behavior**

This is legal.

**Actual Behavior**

```
file.py:190: error: Argument 1 of "b" is incompatible with
supertype "A"; supertype defines the argument type as "str"  [override]
        def b(self, driver: Literal["json", "csv", "parquet"]):
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
file.py:190: note: This violates the Liskov substitution principle
file.py:190: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#incompatible-overrides
```

**Your Environment**

fyi, I ran this in pre-commit, v3.6.0.

- Mypy version used: v1.8.0
- Mypy command-line flags: `--ignore-missing-imports --scripts-are-modules`
- Mypy configuration options from `mypy.ini` (and other config files):

```toml
# I use pyproject.toml to configure mypy.

[tool.mypy]
allow_redefinition = true
check_untyped_defs = true
disallow_incomplete_defs = true
pretty = true
python_version = "3.11"
strict_optional = false
warn_unreachable = true
```
- Python version used: 3.11.7
