### ISSUE TITLE
no-overload-impl false positive with typevar inside

### ISSUE THREAD

**Issue by trim21** [python/mypy#17167]
**Bug Report**

`TypeVar` after overload cause mypy raise a warning about missing impl and redef

(A clear and concise description of what the bug is.)

**To Reproduce**

```python
from typing import Iterable, Sequence, TypeVar, overload


@overload
def chunks(c: str, n) -> Iterable[str]: ...


@overload
def chunks(c: bytes, n) -> Iterable[bytes]: ...


_T = TypeVar("_T")


def chunks(c: Sequence[_T], n) -> Iterable[Sequence[_T]]:
    # looping till length l
    for i in range(0, len(c), n):
        yield c[i : i + n]
```

**Expected Behavior**

should not report errors

**Actual Behavior**

a.py:4: error: An overloaded function outside a stub file must have an implementation  [no-overload-impl]
a.py:15: error: Name "chunks" already defined on line 4  [no-redef]

**Your Environment**

- Mypy version used: 1.9.0
- Mypy command-line flags:
- Mypy configuration options from `mypy.ini` (and other config files):
- Python version used: 3.10

```toml

[tool.mypy]
allow_redefinition = true
ignore_missing_imports = true
check_untyped_defs = true
warn_no_return = false
```
