### ISSUE TITLE
[False Negative] enable_error_codes is completely ignored if any specific code is unrecognised

### ISSUE THREAD

**Issue by ShadowLNC** [python/mypy#17648]
**Bug Report**

If I try to enable an error code which is unrecognised, then the entire `enable_error_codes` option is ignored.

**To Reproduce**

repro.py

```python
x = 3
x += "a"  # type: ignore
```

pyproject.toml

```toml
[project]
name = "my-project"
version = "0"
requires-python = ">=3.9"

[tool.mypy]
python_version = "3.9"
files = "."
enable_error_code = ["ignore-without-code", "not-exists-code"]

incremental = false
cache_dir = "/dev/null"
warn_unused_configs = true
```

**Expected Behavior**

Either mypy should refuse to run and exit nonzero due to unrecognised configuration, or it should act as though I never specified `not-exists-code`, like so:

```shell
repro.py:2: error: "type: ignore" comment without error code (consider "type: ignore[operator]" instead)  [ignore-without-code]
Found 1 error in 1 file (checked 1 source file)
```

**Actual Behavior**

```shell
pyproject.toml: [mypy]: enable_error_code: Invalid error code(s): not-exists-code
Success: no issues found in 1 source file
```

Exit code zero (success)

**Your Environment**

- Mypy version used: `mypy==1.11.1`, `mypy-extensions==1.0.0`, `typing_extensions==4.12.2` (empty Virtual Environment with `pip install mypy` as of today, `mypy --version` gives `mypy 1.11.1 (compiled: yes)`)
- Mypy command-line flags: none (`mypy repro.py`)
- Mypy configuration options from `mypy.ini` (and other config files): as above
- Python version used: Python 3.11.1 (Virtual Environment on macOS, Python installed from https://python.org )
