### ISSUE TITLE
using attrs pre-commit mypy error: Unexpected keyword argument [call-arg]

### ISSUE THREAD

**Issue by sebasouza** [python/mypy#17735]
mypy runs perfectly on terminal, but when running on pre-commit stage, I am getting the error Unexpected keyword argument for every property in my class

```
from attrs import define, field
@define(
    frozen=True,
    kw_only=True,
    slots=True,
    auto_detect=True,
    order=False,
    auto_attribs=True,
)
class MyClass:
   a: str = field(default="")
   b: str = field(default="")

   def myMethod(self) -> Any:
     return MyClass(a=self.a, b="b_value") 
```

mypy pre-commit failed:

error: Unexpected keyword argument "a" for MyClass (line: return MyClass...)

error: Unexpected keyword argument "b" for MyClass (line: return MyClass...)

.pre-commit-config.yaml:

```
 - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        args: ["--config-file", "mypy.ini"]
```
