### ISSUE TITLE
@declared_at method crashes mypy when class is imported from a different module

### ISSUE THREAD

**Issue by andreagrandi** [python/mypy#17739]
**Crash Report**

I have a class named `MyMixin` which has a method like this:
```python
@declared_attr
def price(cls) -> Mapped[Price]:
    return composite(
        CompositeWrapper(Price),
        cls.amount,
        cls.currency,
    )
```
This class is located in module `main` but it's also used (not directly, by importing another class which inherits from this) in module `data`.

When I run: `mypy src/main` I don't get any error, but when I run `mypy src/data` I get: `error: INTERNAL ERROR`

**Traceback**

```
version: 1.11.2
Traceback (most recent call last):
  File "mypy/checkexpr.py", line 5830, in accept
  File "mypy/nodes.py", line 2278, in accept
  File "mypy/checkexpr.py", line 5304, in visit_lambda_expr
  File "mypy/nodes.py", line 2271, in expr
IndexError: list index out of range
```

**To Reproduce**

I can't attach the full code, I'm afraid, but to reproduce it locally I have this class and when I comment out that method, `mypy` never complains (so, across all the source code present in the module, it must be that particular method). If I uncomment the code, then `mypy` crashes when run as explained above.

**Your Environment**

- Mypy version used: 1.11.2
- Mypy command-line flags: `mypy src/data`
- Mypy configuration options from `mypy.ini` (and other config files) - from `pyproject.toml`
```toml
### Mypy - https://mypy.readthedocs.io/en/stable/config_file.html
[tool.mypy]
check_untyped_defs = true
disallow_any_generics = true
allow_untyped_calls = true
allow_untyped_decorators = true
ignore_errors = false
ignore_missing_imports = true
implicit_reexport = false
show_error_codes = true
strict_optional = true
strict_equality = true
no_implicit_optional = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_unused_configs = true
warn_unreachable = true
warn_no_return = true
plugins = ["sqlalchemy.ext.mypy.plugin", "pydantic.mypy"]
```
- Python version used: Python 3.11.7
- Operating system and version: MacOS 14.6.1
