### ISSUE TITLE
Iteration over a Enum fails to typecheck if it's the Flag subclass

### ISSUE THREAD

**Issue by Quasar6X** [python/mypy#17858]
**Bug Report**

Mypy fails to determine the correct type when iterating over `enum.Flag`. The example uses `reduce` from `functools`. The corresponding typeshed [definition](https://github.com/python/typeshed/blob/44aa63330b03bdacab731af2333ff9bf70855de3/stdlib/functools.pyi#L41) for `reduce` looks correct to me. 
Maybe related to #2305 

**To Reproduce**

https://mypy-play.net/?mypy=master&python=3.12&flags=strict&gist=55eabf60ba0d43875271aa8438f04443

**Actual Behavior**

```
main.py:6: error: Incompatible return value type (got "object", expected "Flag")  [return-value]
main.py:6: error: Unsupported left operand type for | ("object")  [operator]
Found 2 errors in 1 file (checked 1 source file)
```

**Your Environment**

I've provided the mypy-play.net link but my environment looked like the following:

- Mypy version used: 1.11.2
- Mypy command-line flags: _None_
- Mypy configuration options from `pyproject.toml`:
```toml
[tool.mypy]
# Maximum strictness level
strict = true
warn_unused_configs = true
enable_error_code = [
    "truthy-bool",
]
enable_incomplete_feature = "NewGenericSyntax"
```
- Python version used: 3.12.6
