### ISSUE TITLE
overriding config for folders (rather than modules)

### ISSUE THREAD

**Issue by chrisjsewell** [python/mypy#17977]
**Feature**

Allow for e.g.

```toml
[[tool.mypy.overrides]]
files = ["scripts/*", "tests/*"]
disallow_any_explicit = false
```

**Pitch**

Currently, it appears one can only apply overrides for certain modules (and their children).
This makes it impossible to use with files not in a package, such a folder of scripts or tests
