### ISSUE TITLE
Flag for only allowing PEP 526 type annotations

### ISSUE THREAD

**Issue by mxr** [python/mypy#5137]
Hello, in a given codebase I wanted to only allow PEP 526 type annotations. I'm currently linting for it with this [`pre-commit`](https://pre-commit.com) hook:

```yaml
- repo: local
  hooks:
  - id: use-type-annotations
    name: type annotations not comments
    entry: '# type.*(?<!: ignore)$'
    language: pygrep
    types: [python]
```

The advantage (for me) is the code is more standardized and lines are slightly shorter, however with the trade-off that you can't wrap `typing` imports in `if TYPE_CHECKING`. I was wondering what mypy maintainers think of a flag to achieve what the lint configuration is doing? (I couldn't find past discussion on this 😅)
