### ISSUE TITLE
Incorrect logical behavior with Union types

### ISSUE THREAD

**Issue by kyprifog** [python/mypy#8798]
Note: if you are reporting a wrong signature of a function or a class in
the standard library, then the typeshed tracker is better suited
for this report: https://github.com/python/typeshed/issues

Please provide more information to help us understand the issue:

* Are you reporting a bug, or opening a feature request?
* Please insert below the code you are checking with mypy,
  or a mock-up repro if the source is private. We would appreciate
  if you try to simplify your case to a minimal repro.
* What is the actual behavior/output?
* What is the behavior/output you expect?
* What are the versions of mypy and Python you are using?
  Do you see the same issue after installing mypy from Git master?
* What are the mypy flags you are using? (For example --strict-optional)
* If mypy crashed with a traceback, please paste
  the full traceback below.

(You can freely edit this text, please remove all the lines
you believe are unnecessary.)

Bug:

Suppose you have two Union types:
```
T1 = Union[A, B]
T2 = Union[C,D]
```
and you construct a statement like this you get the following type behavior:
```
if isinstance(t1, A) and isinstance(t2, C):
     t1: -> A
     t2: -> C
else:
    t1: -> B
    t2: -> D
```

however you should expect it to behave like:

```
if isinstance(t1, A) and isinstance(t2, C):
     t1: -> A
     t2: -> C
else:
    t1: -> Union[A,B]
    t2: -> Union[C,D]
```

Since either t1 or t2 can be false for isinstance in the conditional.
