### ISSUE TITLE
Mypy doesn't find type hints in imported module

### ISSUE THREAD

**Issue by mvolfik** [python/mypy#9944]
**Bug Report**

Mypy doesn't find type hints in my library.

**To Reproduce**

`Pipfile`:

```toml
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]
mypy = "==0.800"

[packages]
kayaclock-utils = {git = "https://github.com/kayaclock/kayaclock-utils.git", ref = "5658111116af089b3b74684a36e284adf6728504"}

[requires]
python_version = "3.8"
```

`program.py`:

```python3
from kayaclock_utils.data.basic_types import GateID

a = GateID(8)
```

Steps:

```bash
pipenv --python 3.8
pipenv update
pipenv run mypy .
```

The [library itself][1] is checked correctly with `mypy` configured to be strict and use `pydantic` plugin, see the [full `mypy.ini`][2]. If i copy this config into the directory with the bug setup as above, nothing changes (just an idea - there maybe should be a way for libraries to define what mypy plugins they recommend/require to typecheck correctly).

[1]: https://github.com/kayaclock/kayaclock-utils/tree/5658111116af089b3b74684a36e284adf6728504
[2]: https://github.com/kayaclock/kayaclock-utils/blob/5658111116af089b3b74684a36e284adf6728504/mypy.ini

**Expected Behavior**

Everything typechecks correctly

**Actual Behavior**

```
program.py:1: error: Skipping analyzing 'kayaclock_utils.data.basic_types': found module but no type hints or library stubs
program.py:1: note: See https://mypy.readthedocs.io/en/latest/running_mypy.html#missing-imports
Found 1 error in 1 file (checked 1 source file)
```

**Your Environment**

- Mypy version used: 0.800
- Mypy command-line flags: none
- Mypy configuration options from `mypy.ini` (and other config files): none or [strict + pydantic][2]
- Python version used: 3.8.5
- Operating system and version: Ubuntu 20.04.1 LTS
